GET http://127.0.0.1:8000/availableMaterialTypes

###

GET http://127.0.0.1:8000/availableTaskTypes

###

POST http://127.0.0.1:8000/registerTaskMaterial

{
    "type": "text",
    "material_information": {
        "text": "Hello World!",
        "metadata": {}
    }
}

###

POST http://127.0.0.1:8000/registerTask

{
    "type": "sql",
    "task": {
        "task_stimulus": {
            "instruction": [
                {
                    "type": "text",
                    "material_information": {
                        "text": "Hello World!",
                        "constraint": [],
                        "metadata": {}
                    }
                }
            ],
            "problem_statement": [{
                    "type": "text",
                    "material_information": {
                        "text": "Hello World!",
                        "metadata": {}
                    }
                }],
            "schema": {
                "type": "schema",
                "material_information": {
                    "schema": "Some schema definition",
                    "name": "Test",
                    "metadata": {}
                }
            },
            "database": {
                "type": "database",
                "material_information": {
                    "database": "CREATE database ...",
                    "name": "Test",
                    "dialect": "postgres",
                    "metadata": {}
                }
            }
        },
        "task_solutions": {
            "query": [{
                "type": "query",
                "material_information": {
                    "query": "SELECT * FROM test;",
                    "metadata": {}
                }
            }]
        }
    }
}